import { Link } from 'react-router-dom';

export default function Privacy() {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4">
      <h1 className="text-3xl font-bold text-purple-600 mb-2">Privacy Policy</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: August 2026</p>

      <div className="flex flex-col gap-6 text-gray-700 text-sm leading-relaxed">

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">1. Information We Collect</h2>
          <p>When you use Groomie, we collect information you provide directly — such as your name, email address, phone number, and payment details — as well as information generated by your use of the platform, including booking history, messages, and reviews. We also collect pet information you enter when making bookings.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">2. How We Use Your Information</h2>
          <p>We use the information we collect to operate and improve the Groomie platform, process bookings and payments, send notifications about your appointments, provide customer support, verify Groomer accounts, and comply with legal obligations. We do not sell your personal information to third parties.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">3. Payment Information</h2>
          <p>Payment card details are processed and stored securely by Stripe. Groomie does not store your full card number, CVV, or expiration date on our servers. Stripe's privacy policy governs the handling of your payment information and can be found at stripe.com/privacy.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">4. Information Shared Between Users</h2>
          <p>To facilitate bookings, certain information is shared between Customers and Groomers — such as your first name, pet information, and profile photo. Your full address, email, and payment details are never shared with other users. Messages sent through the Groomie platform are visible to both participants in the conversation.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">5. Third-Party Services</h2>
          <p>Groomie uses the following third-party services to operate the platform: Stripe (payments), MongoDB Atlas (database hosting), and cloud storage for uploaded files. These providers have their own privacy policies governing their data handling.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">6. Data Retention</h2>
          <p>We retain your account information for as long as your account is active. Booking records and signed waivers are retained for a minimum of 3 years for legal and dispute resolution purposes. You may request deletion of your account by contacting support@groomieapp.com; note that certain records may be retained as required by law.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">7. Cookies</h2>
          <p>Groomie uses essential cookies to maintain your login session. We do not use tracking or advertising cookies. No third-party advertising networks have access to data about your Groomie activity.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">8. Your Rights</h2>
          <p>You have the right to access, correct, or delete the personal information we hold about you. To exercise these rights, contact us at support@groomieapp.com. We will respond within 30 days.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">9. Children's Privacy</h2>
          <p>Groomie is not directed at children under 18. We do not knowingly collect personal information from minors. If you believe a minor has created an account, contact us at support@groomieapp.com.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">10. Changes to This Policy</h2>
          <p>We may update this Privacy Policy from time to time. We will notify registered users of material changes via email. Continued use of the platform after changes are posted constitutes acceptance.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">11. Contact</h2>
          <p>Privacy questions or requests? Email us at <a href="mailto:support@groomieapp.com" className="text-purple-600 hover:underline">support@groomieapp.com</a>.</p>
        </section>

      </div>

      <div className="mt-8 pt-6 border-t text-sm text-gray-400 flex gap-4">
        <Link to="/terms" className="text-purple-600 hover:underline">Terms of Service</Link>
        <Link to="/" className="hover:underline">Back to Home</Link>
      </div>
    </div>
  );
}
